# NumPy ile Lineer Cebir



Asagidaki satirlari calistirarak en altta yer alan odev sorularini yaptiktan sonra dosyanin adini 

ad_soyad_ogrencino 

seklinde degistirerek en gec 21 Subat 23:59'a kadar

[bu adrese](https://stdyildizedu-my.sharepoint.com/:f:/g/personal/sbedir_fbe_yildiz_edu_tr/EtMqKYz3ktxIl16Sh4vGEtIBaA6a3-6uw0nyFtqwNyiCGw) yukleyiniz.

In [1]:
import numpy as np

## NumPy Arrayleri

1D NumPy array bir sayi listesi gibi dusunulebilir. 
2D NumPy arrayleri matrislere karsilik gelir. 
2D NumPy arrayden bir satir veya sutun secersek, sonuc bir 1D NumPy array olur([slice](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#basic-slicing-and-indexing)). 

Karisiklik olmamasi icin her zaman NumPy arraylerimizin tipi(shape), girdi sayisi (size) ve boyutu (dimension) takip edilmelidir.

### Array Attributes

1D (one-dimensional) bir NumPy array olusturup tipi(shape), girdi sayisi (size) ve boyutu (dimension) niteliklerini inceleyelim

In [2]:
a = np.array([1,3,-2,1])
print(a)

[ 1  3 -2  1]


In [3]:
a.ndim

1

In [4]:
a.shape

(4,)

In [5]:
a.size

4

2D (two-dimensional) NumPy array (matris) olusturalim:

In [52]:
M = np.array([[1,2],[3,7],[-1,5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


In [53]:
M.ndim

2

In [54]:
M.shape

(3, 2)

In [55]:
M.size

6

2D NumPy array'den bir satir veya sutun secelim:

In [56]:
col = M[:,1] # M'nin tum satirlarini ve 1.sutununu iceren elemanlar listesini getirir
print(col)

[2 7 5]


In [10]:
col.ndim

1

In [11]:
col.shape

(3,)

In [12]:
col.size

3

Sectigimiz listenin bir sutun vektoru gibi davranmasi icin [reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) metodunu kullanmaliyiz 

In [13]:
print(col)

[2 7 5]


In [14]:
column = np.array([2,7,5]).reshape(3,1)
print(column)

[[2]
 [7]
 [5]]


In [15]:
print('Dimensions:', column.ndim)
print('Shape:', column.shape)
print('Size:', column.size)

Dimensions: 2
Shape: (3, 1)
Size: 3


Ayni icerige sahip olmalarina ragmen `col` ve `column` degiskenleri farkli tipte objelerdir.

In [16]:
print(col)

[2 7 5]


In [17]:
print('Dimensions:',col.ndim)
print('Shape:',col.shape)
print('Size:',col.size)

Dimensions: 1
Shape: (3,)
Size: 3


## Matrislerde Islemler



NumPy arraylerde `+`, `-`, `/`, `*` ve `**` islemleri eleman elemana yapilir.

In [18]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [19]:
M * M

array([[ 9, 16],
       [ 1, 25]])

### Matris Carpimi

NumPy arraylerde matris carpimi icin `@` operatoru kullanilir.

In [20]:
M @ M

array([[ 5, 32],
       [-8, 21]])

In [57]:
col @ column

array([78])

### Birim Matris

In [21]:
I = np.eye(2) #2x2 birim matrisi olusturur.

In [22]:
print(I)

[[1. 0.]
 [0. 1.]]


Simdi 

$$
A = \begin{bmatrix}
1 & 3 \\\
-1 & 7
\end{bmatrix}
\ \ \ \
B = \begin{bmatrix}
5 & 2 \\\
1 & 2
\end{bmatrix}
$$

ve $I$ 2x2 birim matris olmak uzere $2I + 3A - AB$'yi hesaplayalim:

In [23]:
A = np.array([[1,3],[-1,7]])
print(A)

[[ 1  3]
 [-1  7]]


In [24]:
B = np.array([[5,2],[1,2]])
print(B)

[[5 2]
 [1 2]]


In [25]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [40]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

### Matris Kuvvetleri

In [41]:
from numpy.linalg import matrix_power as mpow

In [42]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [43]:
mpow(M,2)

array([[ 5, 32],
       [-8, 21]])

In [44]:
mpow(M,5)

array([[-1525,  3236],
       [ -809,    93]])

In [45]:
M @ M @ M @ M @ M

array([[-1525,  3236],
       [ -809,    93]])

In [46]:
mpow(M,3)

array([[-17, 180],
       [-45,  73]])

In [47]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

###  Transpoz

In [48]:
print(M)

[[ 3  4]
 [-1  5]]


In [49]:
print(M.T)

[[ 3 -1]
 [ 4  5]]


In [50]:
M @ M.T

array([[25, 17],
       [17, 26]])

### Trace (Iz)

In [38]:
np.trace(A)

5

In [43]:
N = np.random.randint(0,10,[2,2])
print(N)

[[1 9]
 [4 3]]


## Odev Sorulari

1. Girdi parametreleri $A$, $i$ ve $j$ olan ve sonuc olarak $A$'nin $i$. ve $j$. satirlarinin ic carpimini donduren bir fonksiyon yaziniz (indexleme 0'dan baslar).
2. $A = \begin{bmatrix} 3 & 4 \\\ -1 & 2 \end{bmatrix}$ ve $B = \begin{bmatrix} 5 & 2 \\\ 8 & -3 \end{bmatrix}$ olmak uzere $AB + 2B^2 - I$ yi hesaplayiniz.
3. Ustteki N matrisi gibi random ureteceginiz bir $4x4$luk $N$ matrisi icin, 
    
    a.) print(N) ile $N$'yi yazdiriniz ve $N$'nin izini bulunuz.
    
    b.) $NN^T$ sonucunu bulunuz.
    
    c.) $NN^T$ sonucu olan matrisin 1. ve 3. satirlarinin ic carpimini 1.soruda yazdiginiz fonksiyonu kullanarak bulunuz.

In [72]:
def satir_ic_carpim(A,i,j):
    # Eger i satir indexi disinda olursa hata dondurmeli: Satir indexi 0'dan baslar, A.shape[0]-1'e kadar gider.
    if #####: 
        return "i matris satir indeksi disinda! lutfen i icin gecerli bir deger seciniz."
    # Eger j satir indexi disinda olursa hata dondurmeli: Satir indexi 0'dan baslar, A.shape[0]-1'e kadar gider.
    elif #####:
        return "j matris satir indeksi disinda! lutfen j icin gecerli bir deger seciniz."
    # Tek satir kodla
        # A'nin i.satirini secmeli
        # A'nin j.satirini secip sutun matrisine cevirmeli
        # Bu ikisinin matris carpimini bulmali
        # Sonucu tamsayiya cevirmelisiniz. (int(deger) deger'i tamsayiya cevirir)
    else:
        return #####
    
    ## Asagidakileri yaparak fonksiyonunuzun dogrulugunu kontrol ediniz.

In [74]:
M

array([[ 1,  2],
       [ 3,  7],
       [-1,  5]])

In [76]:
satir_ic_carpim(M,-1,1)

'i matris satir indexi disinda! lutfen i icin gecerli bir deger seciniz.'

In [77]:
satir_ic_carpim(M,3,1)

'i matris satir indexi disinda! lutfen i icin gecerli bir deger seciniz.'

In [79]:
satir_ic_carpim(M,1,-1)

'j matris satir indexi disinda! lutfen j icin gecerli bir deger seciniz.'

In [80]:
satir_ic_carpim(M,1,3)

'j matris satir indexi disinda! lutfen j icin gecerli bir deger seciniz.'

In [82]:
satir_ic_carpim(M,1,1)

58

In [ ]:
#2.sorunun Cevabi:


In [ ]:
#3.sorunun Cevabi: